config/routes.rb
Rails.application.routes.draw do
  resources :books
  patch '/books/:id', to: 'books#update', as: 'update_book'
  #get '/top' => 'homes#top'
  #root 'books#index'
  root 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  #has_one_attached :image
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成(2023/02/22 17:13)
  #@list = List.new
  end


  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice:'Book was successfully created.'
    #else
    #render :new
    else  
    @books = Book.all  # 投稿一覧を再取得する
    render :index  # 投稿一覧と新規投稿フォームを表示する
    end
  end

  def index
    @books = Book.all
    @book = Book.new #変更前は.new
    #@list = List.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end


 # def update
 #  book = Book.find(params[:id])
 #   if
 #    book.update(book_params)
 #    redirect_to book_path(book.id), notice: "Book was successfully created."
 #    
 #   else
 #    @books = Book.all
 #    render :index
 #   end
 # end


def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to book_path, notice: "Book was successfully creatred."
  else
    render :edit
  end
end



  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to "/books"  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title, class: "form-control", value: @book.title %>
  <h4>Body</h4>
  <%= f.text_area :body, class: "form-control", value: @book.body %>
  <p>
　<%= f.submit "Update Book" %>
　</p>

　<%= link_to "Show", "/books/#{@book.id}" %>
　<%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td>
          <%= link_to 'Show', "/books/#{book.id}" %>
        </td>
        <td>
          <%= link_to 'Edit', edit_book_path(book.id) %>
        </td>
        <td>
          <%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you Sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!-- form_withにオプション追記 -->
<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <p>
  <%= f.submit 'Create Book' %>
  </p>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!-- form_withにオプション追記 -->
<%= form_with model: @list, url: '/lists', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <p>
  <%= f.submit 'Create Book' %>
  </p>
<% end %>

app/views/books/show.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<h2>Title</h2>
<p><%= @book.title %></p>

<h2>Body</h2>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>












<!--%= link_to "Edit", edit_list_path(@list.id) %>
<!--%= link_to "Back", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>
<strong>Bookers</strong>
では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<p>
<%= link_to "start", books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>